import logging
import re
from datetime import datetime

from me4storage.models.basemodel import Model
import me4storage.common.formatters as formatters

logger = logging.getLogger(__name__)

class Disk(Model):
    ''' Class to represent the drives model from the ME4 API
    https://www.dell.com/support/manuals/uk/en/ukbsdt1/powervault-me4012/me4_series_cli_pub/drives?guid=guid-7edb7fca-44ce-410d-a670-948e18619a68&lang=en-us
    '''
    _attrs = {
        'durable-id': '',
        'enclosure-id': '',
        'drawer-id': '',
        'slot': '',
        'location': '',
        'url': '',
        'port': '',
        'scsi-id': '',
        'blocksize': '',
        'blocks': '',
        'serial-number': '',
        'vendor': '',
        'model': '',
        'revision': '',
        'secondary-channel': '',
        'container-index': '',
        'member-index': '',
        'description': '',
        'description-numeric': '',
        'architecture': '',
        'architecture-numeric': '',
        'interface': '',
        'interface-numeric': '',
        'single-ported': '',
        'single-ported-numeric': '',
        'type': '',
        'type-numeric': '',
        'usage': '',
        'usage-numeric': '',
        'smart-numeric': '',
        'dual-port': '',
        'error': '',
        'fc-p1-channel': '',
        'fc-p1-device-id': '',
        'fc-p1-node-wwn': '',
        'fc-p1-port-wwn': '',
        'fc-p1-unit-number': '',
        'fc-p2-channel': '',
        'fc-p2-device-id': '',
        'fc-p2-node-wwn': '',
        'fc-p2-port-wwn': '',
        'fc-p2-unit-number': '',
        'drive-down-code': '',
        'owner': '',
        'owner-numeric': '',
        'index': '',
        'rpm': '',
        'size': '',
        'size-numeric': '',
        'sector-format': '',
        'sector-format-numeric': '',
        'transfer-rate': '',
        'transfer-rate-numeric': '',
        'attributes': '',
        'attributes-numeric': '',
        'enclosure-wwn': '',
        'enclosure-url': '',
        'status': '',
        'recon-state': '',
        'recon-state-numeric': '',
        'disk-dsd-count': '',
        'spun-down': '',
        'number-of-ios': '',
        'total-data-transferred': '',
        'total-data-transferred-numeric': '',
        'avg-rsp-time': '',
        'fde-state': '',
        'fde-state-numeric': '',
        'lock-key-id': '',
        'import-lock-key-id': '',
        'fde-config-time': '',
        'fde-config-time-numeric': '',
        'temperature': '',
        'temperature-numeric': '',
        'temperature-status': '',
        'temperature-status-numeric': '',
        'power-on-hours': '',
        'extended-status': '',
        'health': '',
        'health-numeric': '',
        'health-reason': '',
        'health-recommendation': '',
        }
